/**
 * Client-side markdown transcript (fallback when server export is unavailable).
 * Matches the spirit of backend buildSessionMarkdown for local/streaming views.
 */

export type LocalTranscriptMessage = {
  role: "user" | "assistant";
  content: string;
  createdAt?: string;
};

function stamp(iso?: string): string {
  if (!iso) return new Date().toISOString().replace("T", " ").replace(/\.\d{3}Z$/, " UTC");
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return iso;
  return new Date(t).toISOString().replace("T", " ").replace(/\.\d{3}Z$/, " UTC");
}

export function buildLocalTranscriptMarkdown(options: {
  characterName: string;
  characterId?: string | null;
  sessionId?: string | null;
  resumeCode?: string | null;
  messages: LocalTranscriptMessage[];
}): string {
  const name = options.characterName || "Character";
  const lines: string[] = [
    `# ${name}`,
    "",
    `> Procharacters.cloud transcript · ${options.messages.length} messages`,
    "",
    "| | |",
    "|---|---|",
    `| Character | ${name}${options.characterId ? ` (\`${options.characterId}\`)` : ""} |`,
  ];
  if (options.sessionId) {
    lines.push(`| Session | \`${options.sessionId}\` |`);
  }
  if (options.resumeCode) {
    lines.push(`| Resume code | \`${options.resumeCode}\` |`);
  }
  lines.push(`| Exported | ${stamp()} |`, "", "---", "", "## Conversation", "");

  if (options.messages.length === 0) {
    lines.push("_No messages yet._", "");
  } else {
    for (const msg of options.messages) {
      const who = msg.role === "user" ? "You" : name;
      lines.push(`### ${who}`);
      if (msg.createdAt) lines.push(`*${stamp(msg.createdAt)}*`, "");
      else lines.push("");
      lines.push(msg.content.includes("```") ? msg.content.replace(/```/g, "'''") : msg.content);
      lines.push("");
    }
  }

  lines.push("---", "", "_Generated by Procharacters.cloud · Uncensored 18+ · KGC Ventures_", "");
  return lines.join("\n");
}
